# Generated by Django 3.2.8 on 2023-03-14 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('types', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('types', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=255, null=True)),
                ('info', models.TextField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('company_type', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time_min', models.CharField(max_length=255, null=True)),
                ('work_time_max', models.CharField(max_length=255, null=True)),
                ('work_money_min', models.CharField(max_length=255, null=True)),
                ('work_money_max', models.CharField(max_length=255, null=True)),
                ('education', models.CharField(max_length=255, null=True)),
                ('info', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.einfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('types', models.IntegerField(default=0)),
                ('school', models.CharField(max_length=255, null=True)),
                ('age', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(max_length=255, null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('realname', models.CharField(max_length=255, null=True)),
                ('hope_work_time_min', models.CharField(max_length=255, null=True)),
                ('hope_work_time_max', models.CharField(max_length=255, null=True)),
                ('hope_work_money_min', models.CharField(max_length=255, null=True)),
                ('hope_work_money_max', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JoinWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pass_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo')),
            ],
        ),
    ]
