# Generated by Django 3.2.8 on 2023-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshort',
            name='job_tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
