# Generated by Django 3.2.8 on 2023-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workshort_job_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='work_time_max',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='work_time_min',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='info',
            new_name='job_overview',
        ),
        migrations.AddField(
            model_name='einfo',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='einfo',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='einfo',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_and_qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.TextField(null=True),
        ),
    ]
