# Generated by Django 3.2.8 on 2023-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230314_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
