# Generated by Django 3.2.8 on 2023-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230314_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinwork',
            name='msg',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
