# Generated by Django 3.2.8 on 2023-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_joinwork_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='types',
            field=models.IntegerField(default=2),
        ),
    ]
