# Generated by Django 3.2.8 on 2023-03-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_einfo_ountry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='einfo',
            old_name='ountry',
            new_name='country',
        ),
    ]
