# Generated by Django 3.2.8 on 2023-03-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_ountry_einfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='einfo',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
